apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tetra-production
resources:
  - ../../base
  - namespace.yaml
  - sealed-secrets.yaml
patches:
  - path: web-patch.yaml
  - path: api-patch.yaml
  - path: ingress-patch.yaml
images:
  - name: tetramobile/tetra-web
    newTag: latest
  - name: tetramobile/tetra-api
    newTag: latest
